// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmCcBsbGah2kEHsXk10o-IcpWMjm7OxHk',
    appId: '1:53571317085:web:bf8e5031a99a928f158cb4',
    messagingSenderId: '53571317085',
    projectId: 'balajipoints',
    authDomain: 'balajipoints.firebaseapp.com',
    storageBucket: 'balajipoints.firebasestorage.app',
    measurementId: 'G-BRYRJMN6EF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1sfFB_qTXzIGaI0QonxGEZo8MICouGzU',
    appId: '1:53571317085:android:9a0a2f059605eb97158cb4',
    messagingSenderId: '53571317085',
    projectId: 'balajipoints',
    storageBucket: 'balajipoints.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8VLmXUSOFNyPHdNhi1gYTnLvQSY8zbnI',
    appId: '1:53571317085:ios:4149180898927b5f158cb4',
    messagingSenderId: '53571317085',
    projectId: 'balajipoints',
    storageBucket: 'balajipoints.firebasestorage.app',
    iosBundleId: 'com.balaji.points',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8VLmXUSOFNyPHdNhi1gYTnLvQSY8zbnI',
    appId: '1:53571317085:ios:4149180898927b5f158cb4',
    messagingSenderId: '53571317085',
    projectId: 'balajipoints',
    storageBucket: 'balajipoints.firebasestorage.app',
    iosBundleId: 'com.balaji.points',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmCcBsbGah2kEHsXk10o-IcpWMjm7OxHk',
    appId: '1:53571317085:web:0c6636c806fa28de158cb4',
    messagingSenderId: '53571317085',
    projectId: 'balajipoints',
    authDomain: 'balajipoints.firebaseapp.com',
    storageBucket: 'balajipoints.firebasestorage.app',
    measurementId: 'G-1DYKJ23TN0',
  );
}
